### ISSUE TITLE
Scrabble frequency and scores

### ISSUE THREAD

**Issue by rrees** [guardian/coding-exercises#34]
I wondering whether the Scrabble tile scores and distributions should just be provided as a JSON file for this problem?

In my experience no-one has really taken a different approach to solving this, they all look it up on Wikipedia and create a map.

Things like bag and hand creation are much more varied and interesting.

**Comment by alexduf** [comment]
To balance that, I found it useful to see if people know about data structures. I have encountered candidates who didn't know how to model it, and didn't think about using Maps

**Comment by akash1810** [comment]
I've found this part of the exercise a good way to assess a candidate's pragmatism; the time limitation plays a role in how the bag of letters is represented. Equally, I've found it useful to see how the bag evolves when code from previous tasks is reused.

**Comment by mxdvl** [comment]
As these exercises are used for all engineering levels I think it’s best to not make assumptions about what the candidate knows about data structures, or make decisions on their behalf.

**Comment by akash1810** [comment]
Closing as the comments suggest we find value in allowing candidates to decide how to represent tile scores and distributions.
