### ISSUE TITLE
Rename repo to pairing-exercises

### ISSUE THREAD

**Issue by rtyley** [guardian/coding-exercises#39]
Discussed with @akash1810 & @amyhughes

**Comment by amyhughes** [comment]
👍 Much nicer!

**Comment by alexduf** [comment]
I think it's a good idea too

**Comment by roppa** [comment]
I had an interview with an idiot from 101ways who called this a 'pair programming challenge' who used this repo (I think he used to work for you). I asked if he was the navagator in this and he got his knickers in a twist. There is nothing 'pair' about this. It is a coding challenge! It also indicates that there will be exactly 2 people involved. I would suggest remove 'pair[ing]' and call it something like 'coding-exercises' or 'technical-interview-exercises'

**Comment by akash1810** [comment]
Hi @roopa, thank you for your feedback. Our intent behind this issue isn’t especially intention revealing so, for future generations, our motivation was to use less intimidating language. That is, during an internal training session, we concluded `exercises` is more approachable at all levels we hire for.

On further inspection, `pairing-exercises` doesn’t entirely reflect our usage of this repo. For some roles, we perform an additional remote pairing test at the end of the phone interview; this is a two on one exercise and thus not technically a pair. `coding-exercises` is more suitable and we are renaming accordingly.

We’re always looking to improve and value feedback. Indeed this was one of the motivations to making this repository public. Read more about this [here](https://www.theguardian.com/info/developer-blog/2016/jan/20/the-guardians-new-pairing-exercises).

We continuously seek to improve our hiring process as a whole, making it as accessible, inclusive, friendly and constructive as possible for candidates. More information about our culture can be found on our [blog](https://www.theguardian.com/info/series/digital-blog).

It is important to mention that we don’t tolerate exclusionary language in our spaces, including public repos. So please refrain from referring to another person as an idiot. We understand you have had a negative experience, but let’s not continue the negativity here.

**Comment by roppa** [comment]
Great! Idiot may have sounded strong, but it was one of the worst interviews I’ve had
